title_name = "Call of Duty - World at War (Sep 27, 2008 Prototype)" # MP
title_id = "4156081C" # AV-2076
hash = "996333F652838DCF" # CoDMP.exe
#media_id = "00000000"

[[patch]]
    name = "Fixed on-startup crash"
    desc = "Something related to memory."
    author = "Adrian"
    is_enabled = false

    [[patch.be32]]
        address = 0x8246d39c
        value = 0x60000000

[[patch]]
    name = "Fixed black screen on start-up"
    desc = "Skip connecting to blackbox server."
    author = "Adrian"
    is_enabled = false

    [[patch.be32]]
        address = 0x828726a8
        value = 0x60000000
