title_name = "Family Guy: Back to the Multiverse" # BTTM
title_id = "415608C5"
hash = "F3CB75CAEB34325C"
#media_id = ""

[[patch]]
    name = "Fix hang on BINK videos"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x82636A9C
        value = 0x2B0B0000
