title_name = "GoldenEye 007: Reloaded" # GE
title_id = "415608AF" # AV-2223
hash = "7FFAE33DD2045CE7"
#media_id = "40583A82" http://redump.org/disc/38456

[[patch]]
    name = "Lens Flare Occlusion Fix"
    desc = "Fixes bright lights that aren't properly occluded."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8248CB40
        value = 0x48000DB8
