title_name = "Family Guy: Back to the Multiverse" # BTTM
title_id = "415608C5" # AV-2245
#hash = "" # DEFAULT.XEX
#media_id = "55DA4FA1" http://redump.org/disc/55407

[[patch]]
    name = "Fix hang on BINK videos"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x82636A9C
        value = 0x2B0B0000
