title_name = "Transformers: Rise of The Dark Spark"
title_id = "41560904"
hash = "3D80DDB6879F0E01"
#media_id = "50D83F2D"

[[patch]]
    name = "Disable Lens Flares"
    desc = "Fixes unoccluded bright lights on-screen."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82808CAC
        value = 0x39400000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82B5CE6C
        value = 0x38A00010
