title_name = "Resident Evil 5"
title_id = "434307D4"
hash = "9E761F58D8ADFBC4"
#media_id = "5B2A79D5"

[[patch]]
    name = "Remove All Your Money"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x8250A69C
        value = 0x60000000

[[patch]]
    name = "Buy Items While Broke"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x821BC1A4
        value = 0x60000000

[[patch]]
    name = "Unlimited Money"
    desc = "Buy items without losing money."
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x82505274
        value = 0x60000000

[[patch]]
    name = "Unlimited Ammo"
    desc = "No ammo is used."
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x827597D0
        value = 0x60000000

[[patch]]
    name = "Never Get Hit"
    desc = "Turns off hit damage done to the player. You can still die if grabbed."
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x8264337C
        value = 0x60000000
