title_name = "Asura's Wrath"
title_id = "43430817"
hash = "F3AA3A3085A3A3B9"
#media_id = "11DFADD6"

[[patch]]
    name = "Unlock FPS"
    desc = "Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config. Button mashing QTEs are tied to framerate and when vsync is disabled it's difficult to correctly time them."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x824D7130
        value = 0x60000000
    [[patch.be8]]
        address = 0x8299A70F
        value = 0x01

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x828D921C
        value = 0x38A00010

[[patch]]
    name = "Resolution Scaling Fix / Disable All Post-Processing"
    desc = "Dramatically changes the overall look of the game, but fixes all edge-detection overcorrection and color smearing."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8273F610
        value = 0x38A00001
    [[patch.be32]]
        address = 0x8273F76C
        value = 0x38A00000
    [[patch.be32]]
        address = 0x8273F8D8
        value = 0x38800004
    [[patch.be32]]
        address = 0x82741ED4
        value = 0x38A00000
    [[patch.be32]]
        address = 0x82741EF0
        value = 0x60000000
