title_name = "Leisure Suit Larry: Box Office Bust"
title_id = "434D0822" # CM-2082
hash = "4D8B43915E41A1EA" # default.xex
#media_id = "536000E3" # Disc (USA, Europe): http://redump.org/disc/14255

[[patch]]
    name = "Unlock FPS"
    desc = "See note about framerate patches in the README."
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x82507504
        value = 0x60000000
