title_name = "Leisure Suit Larry: Box Office Bust"
title_id = "434D0822" # CM-2082
hash = "654C4EEDC39B5972" # default.xex
#media_id = "536000E3" http://redump.org/disc/14255

[[patch]]
    name = "Unlock FPS"
    desc = "Requires vsync to be changed from true to false in the Xenia config to go above 60 FPS."
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x82507504
        value = 0x60000000
