title_name = "Onechanbara"
title_id = "445007EA" # DP-2026
#hash = "" # default.xex
#media_id = ""

[[patch]]
    name = "Invincibility"
    author = "Eto"
    is_enabled = false

    [[patch.be32]]
        address = 0x821FBA64
        value = 0x60000000

[[patch]]
    name = "No Splatter Gauge"
    author = "Eto"
    is_enabled = false

    [[patch.be32]]
        address = 0x822E5868
        value = 0x60000000

[[patch]]
    name = "Unlimited Pistol/Shotgun/SMG Ammo"
    author = "Eto"
    is_enabled = false

    [[patch.be32]]
        address = 0x82328AB4
        value = 0x60000000
