title_name = "Mirror's Edge"
title_id = "45410850" # EA-2128
hash = "25AA0820DF95AA47" # default.xex
#media_id = [
#    "426CA5A2", # Disc (Europe): http://redump.org/disc/11415
#    "214A9845", # Disc (USA):    http://redump.org/disc/15254
#]

[[patch]]
    name = "Unlock FPS"
    desc = "Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config."
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8254f5fc
        value = 0x60000000
    [[patch.be8]]
        address = 0x8281492b
        value = 0x01

[[patch]]
    name = "Dynamic Lighting & Shadows Shading Fix"
    desc = "Solves most dynamic lighting artifacts, like splotchy skin complexion & invisible hands and feet, caused by an issue with MSAA tiling."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x823aa2e0
        value = 0x39200000
    [[patch.be32]]
        address = 0x823aa350
        value = 0x39200000

[[patch]]
    name = "Disable Lens Flares"
    desc = "Fixes unoccluded bright lights on-screen."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8233ac08
        value = 0x39400000

[[patch]]
    name = "Disable Motion Blur"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8239ad24
        value = 0x3af50000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8239cf0c
        value = 0x39600010

[[patch]]
    name = "Disable Bloom & Depth of Field"
    author = "illusion"
    is_enabled = false

    [[patch.be8]]
        address = 0x8270f018
        value = 0x40
