title_name = "Rock Band 3"
title_id = "45410914" # EA-2324
hash = "A6CD6E2BDF0A7007" # TODO: Add module filename
#media_id = ""

[[patch]]
    name = "Skip SEH usage to prevent nullptr write"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x8226045C
        value = 0x485B5DDC
