title_name = "NFS Most Wanted" # Need for Speed 2005
title_id = "454107D9"
hash = "AAB47567B8183E97"

[[patch]]
    name = "Disable Post Processing"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x82224710
        value = 0x39400000
    [[patch.be32]]
        address = 0x8222442C
        value = 0x39200000

[[patch]]
    name = "Skip audio loop stuck code"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x825E1D3C
        value = 0x2F050001
    [[patch.be32]]
        address = 0x825E1D40
        value = 0x419A0010
