title_name = "Hail to the Chimp"
title_id = "475007D2"
hash = "B9ED675097ECB955"
#media_id = ""

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8268F517
        value = 0x01
