title_name = "El Shaddai"
title_id = "494F07D1" # IO-2001
hash = "34A73675FE9488AB" # DEFAULT.XEX
#media_id = "640B378B" http://redump.org/disc/42246

[[patch]]
    name = "1920x1080 Resolution"
    desc = "Original resolution is 1120x584."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x82220B20
        value = 0x60000000

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1120x584."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x82220B36
        value = 0x02D0
    [[patch.be16]]
        address = 0x82220B32
        value = 0x0500

[[patch]]
    name = "960x540 Resolution"
    desc = "Original resolution is 1120x584."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x82220B36
        value = 0x021C
    [[patch.be16]]
        address = 0x82220B32
        value = 0x03C0
