title_name = "Silent Hill: Downpour"
title_id = "4B4E0823" # KN-2083
hash = "BEE670772E454B1F" # default.xex
#media_id = "7D387D17" http://redump.org/disc/58138

[[patch]]
    name = "Unlock FPS"
    desc = "Camera movement slows down over 60 FPS. Framerates above 60 FPS require vsync to be changed from true to false in the Xenia config."
    author = "illusion, Aphelion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x825C64C8
        value = 0x60000000
    [[patch.be8]]
        address = 0x82D20F83
        value = 0x01

[[patch]]
    name = "Disable FXAA"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82A1097C
        value = 0x39600000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x829D342C
        value = 0x38A00010
