title_name = "LEGO Star Wars III: The Clone Wars" # 3
title_id = "4C4107F3" # LA-2035
#hash = "" # Default.xex
#media_id = "563D3E40" http://redump.org/disc/38506

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x82A2E70F
        value = 0x01
