title_name = "LEGO Star Wars: The Complete Saga"
title_id = "4C4107D7" # LA-2007
#hash = "" # Default.xex
#media_id = "5E486FF7" http://redump.org/disc/38504

[[patch]]
    name = "Allow Swears"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8200F241 # badwords.txt
        value = 0x34         # First char
