title_name = "Halo: Reach"
title_id = "4D53085B" # MS-2139
hash = "DC167618365E3A8C" # default.xex
#media_id = "566C10D3" http://redump.org/disc/16109

[[patch]]
    name = "Aspect Ratio"
    desc = "Makes FMVs stretch vertically. See note about aspect ratio patches in README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x82047C38
        value = 0x4018E38E
