title_name = "Banjo-Kazooie: Nuts & Bolts" # And, N&B
title_id = "4D5307ED" # MS-2029
hash = "C6433BB2BA42398B" # default.xex
#media_id = "3E567DFF" http://redump.org/disc/11831

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8228A83B
        value = 0x01

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82B96D7C
        value = 0x38A00010
    [[patch.be32]]
        address = 0x82B96E10
        value = 0x38A00010
    [[patch.be32]]
        address = 0x82B96E10
        value = 0x38A00010
    [[patch.be32]]
        address = 0x82B96B98
        value = 0x38A00010
    [[patch.be32]]
        address = 0x823A8308
        value = 0x38A00010

[[patch]]
    name = "Disable Motion Blur"
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x8229F480
        value = 0x4800

[[patch]]
    name = "Disable SSAO"
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x8235F350
        value = 0x4800

[[patch]]
    name = "Notes Never Decrease"
    author = "Etokapa, Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x8250C3B0
        value = 0x60000000

[[patch]]
    name = "Screen Always Bright"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x829DD0D4
        value = 0x60000000
