title_name = "Halo 3 Alpha"
title_id = "4D53880C"

[[patch]]
    name = "More Debug Logs"
    desc = "This halo build contains some logging functionality, when enabled the game will write more logs to cache\reports."
    author = "craftycodie"
    is_enabled = false

    [[patch.be32]]
        address = 0x823B23D0
        value = 0x60000000
