title_name = "Viva Pi√±ata"
title_id = "4D5307F2" # MS-2034
hash = "B5434A4059519980" # default.xex
#media_id = "690B3287" http://redump.org/disc/11854

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8246AB54
        value = 0x01
