title_name = "Perfect Dark: Zero"
title_id = "4D5307D3" # MS-2003
hash = "8AB05ACA5F683CD4" # default.xex
#media_id = "41EEAFCB" http://redump.org/disc/11810

[[patch]]
    name = "Unlock FPS"
    desc = "Requires vsync to be changed from true to false in the Xenia config to go above 60 FPS."
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x826CFB75
        value = 0x00

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x820EC158
        value = 0x4018E38E

[[patch]] # TODO(illusion): Need to test with picked up weapons.
    name = "Bottomless Clip"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x825744A8
        value = 0x4E800020
    [[patch.be16]]
        address = 0x8220D138
        value = 0x4800
