title_name = "Halo: Reach"
title_id = "4D53085B"
hash = "DC167618365E3A8C"
#media_id = ""

[[patch]]
    name = "Aspect Ratio"
    desc = "Makes FMVs stretch vertically. See note about aspect ratio patches in README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x82047C38
        value = 0x4018E38E
