title_name = "Banjo-Kazooie: Nuts & Bolts" # And, N&B
title_id = "4D5307ED" # MS-2029
hash = "C03916823ADAC91B" # default.xex
#media_id = "3E567DFF" # Disc (USA): http://redump.org/disc/11831

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8228a83b
        value = 0x01

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82b96d7c
        value = 0x38a00010
    [[patch.be32]]
        address = 0x82b96e10
        value = 0x38a00010
    [[patch.be32]]
        address = 0x82b96b98
        value = 0x38a00010
    [[patch.be32]]
        address = 0x823a8308
        value = 0x38a00010

[[patch]]
    name = "Disable Motion Blur"
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x8229f480
        value = 0x4800

[[patch]]
    name = "Disable SSAO"
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x8235f350
        value = 0x4800
[[patch]]
    name = "Disable LoD"
    author = "retroben"
    is_enabled = false

    [[patch.be32]]
        address = 0x82b680f8
        value = 0x48000018

[[patch]]
    name = "Notes Never Decrease"
    author = "Etokapa, Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x8250c3b0
        value = 0x60000000

[[patch]]
    name = "Fuel and Ammo Never Decreases"
    author = "retroben"
    is_enabled = false

    [[patch.be32]]
        address = 0x822784e8
        value = 0x60000000

[[patch]]
    name = "Max Acquired Parts Access"
    author = "retroben"
    is_enabled = false

    [[patch.be32]]
        address = 0x8251d428
        value = 0x38e000ff
    [[patch.be32]]
        address = 0x8251dccc
        value = 0x394000ff
    [[patch.be32]]
        address = 0x8255ed1c
        value = 0x392000ff

[[patch]]
    name = "Extended Build Range"
    author = "retroben"
    is_enabled = false

    [[patch.be32]]
        address = 0x8264ac14
        value = 0x2f09001f
    [[patch.be32]]
        address = 0x8264ac30
        value = 0x2f09001f
    [[patch.be32]]
        address = 0x8264ac4c
        value = 0x2f0b001f
    [[patch.be32]]
        address = 0x8264ad38
        value = 0x21290020
    [[patch.be32]]
        address = 0x8264ada8
        value = 0x216b0020

[[patch]]
    name = "Screen Always Bright"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x829dd0d4
        value = 0x60000000
