title_name = "Halo: Reach" # TU1
title_id = "4D53085B" # MS-2139
hash = "DBC44902DBD3BCD8" # default.xex
#media_id = "566C10D3" # Disc (World): http://redump.org/disc/16109

[[patch]]
    name = "Disable Lens Flares"
    desc = "Removes unoccluded bright lights on-screen."
    author = "boma, Sowa_95"
    is_enabled = false

    [[patch.be16]]
        address = 0x822453b4
        value = 0x4800
