title_name = "Viva Pi√±ata: Trouble in Paradise" # TIP
title_id = "4D53085F" # MS-2143
hash = "B6AB7E714A5904D3" # default.xex
#media_id = "76A44A5D" http://redump.org/disc/67404

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8229B71F
        value = 0x01
