title_name = "Lost Odyssey"
title_id = "4D5307FA"
#hash = "4FA944560B7A49F7" # Disc 1
#hash = "D3811D4222F38F9D" # Disc 2
#hash = "61FA38436DB33BCE" # Disc 3
#hash = "FA5C9CBE5DED16BA" # Disc 4
#media_id = "612E5362"

[[patch]]
    name = "60 FPS"
    desc = "Disabling vsync in Xenia config for over 60 FPS is not recommended as it causes numerous gameplay issues."
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x827B3F37
        value = 0x01

[[patch]]
    name = "Disable Depth of Field"
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x82305F6C
        value = 0x40

[[patch]]
    name = "Disable Motion Blur"
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x826E12CC
        value = 0x40

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x823B8EB7
        value = 0x10

[[patch]]
    name = "Disable Dynamic Shadows"
    desc = "Provides a moderate performance boost, especially when using custom resolution scaling."
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x823D5C9C
        value = 0x4800
    [[patch.be16]]
        address = 0x823D5768
        value = 0x4800
    [[patch.be32]]
        address = 0x823DD7A0
        value = 0x60000000
