title_name = "Forza Motorsport 4"
title_id = "4D530910" # MS-2320
hash = "7566081090ECD4EC"
#media_id = ""

[[patch]]
    name = "Square Shadow Fix"
    author = "illusion"
    is_enabled = false

    [[patch.be8]]
        address = 0x828DF12B
        value = 0x01
