title_name = "Kameo: Elements of Power"
title_id = "4D5307D2" # MS-2002
hash = "EE52F3EB68FFE487" # default.xex
#media_id = ""

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x820CF93F
        value = 0x01

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x82087CAC
        value = 0x4018E38E
