title_name = "Halo 3: ODST"
title_id = "4D530877"
hash = "D9B82039CB60493E"
#media_id = ""

[[patch]]
    name = "Aspect Ratio"
    desc = "Makes FMVs stretch vertically. See note about aspect ratio patches in README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x8203D6B4
        value = 0x4018E38E
