title_name = "Forza Horizon"
title_id = "4D5309C9" # MS-2505
hash = "F68A4156E4D07529" # default.xex
#media_id = "2B7A1346" http://redump.org/disc/84331

[[patch]]
    name = "Disable Motion Blur"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x82D7894C
        value = 0x60000000

[[patch]]
    name = "Disable Depth of Field"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x8245B494
        value = 0x39600000
    [[patch.be32]]
        address = 0x8245846C
        value = 0x39600000
    [[patch.be32]]
        address = 0x8245849C
        value = 0x39600000

[[patch]]
    name = "Disable Shadows"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x824408B0
        value = 0x39600000
    [[patch.be32]]
        address = 0x82442478
        value = 0x39600000

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x829EF74F
        value = 0x01
    [[patch.be8]]
        address = 0x829EF763
        value = 0x01
