title_name = "Batman: Arkham Asylum GOTY" # Game Of The Year
title_id = "5343080B" # SC-2059
hash = "FAA969D8A240F7FC" # Default.xex
#media_id = "71D29B88" http://redump.org/disc/68344

[[patch]]
    name = "Debug Menu"
    author = "dron_3" # https://dron-3.blogspot.com/2020/11/batman-arkham-series-xbox-360-debug-menu.html
    is_enabled = false

    [[patch.be8]]
        address = 0x82749FDF
        value = 0x00
    [[patch.be8]]
        address = 0x82749FFB
        value = 0x00
