title_name = "Bionicle Heroes"
title_id = "534307E2" # SC-2018
hash = "6B1A9BEF4F93EC7B" # default.xex
#media_id = "39D1B5B2" http://redump.org/disc/16209

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8228D763
        value = 0x01
