title_name = "Sonic the Hedgehog" # 2006
title_id = "534507D6"
hash = "3FAD43EC51B87429"
#media_id = ""

[[patch]]
    name = "Disable 2x MSAA"
    desc = "Disables 2x MSAA, which is used during gameplay (except for super speed sections). Can significantly improve performance, especially in the town areas."
    author = "Hyper"
    is_enabled = false

    [[patch.be32]]
        address = 0x82607B94
        value = 0x38800000

[[patch]]
    name = "Disable 4x MSAA"
    desc = "Disables 4x MSAA, which is used only for the main menu."
    author = "Hyper"
    is_enabled = false

    [[patch.be32]]
        address = 0x82607BB8
        value = 0x38800000

[[patch]]
    name = "Disable Bloom"
    desc = "Disables bloom. Mostly useful for upscaling and doesn't have any sort of performance impact."
    author = "Hyper"
    is_enabled = false

    [[patch.be32]]
        address = 0x8260A448
        value = 0x48000094

[[patch]]
    name = "Disable Radial Blur"
    desc = "Disables radial blur when moving at high speed."
    author = "Hyper"
    is_enabled = false

    [[patch.be32]]
        address = 0x8204C584
        value = 0x8260A5B0

[[patch]]
    name = "Disable Shadows"
    desc = "Disables shadow rendering. Can significantly improve performance if you're willing to give up decent lighting."
    author = "Hyper"
    is_enabled = false

    [[patch.be32]]
        address = 0x8260CE40
        value = 0x48000204
