title_name = "SONIC UNLEASHED" # TU2
title_id = "53450812" # SE-2066
hash = "C33BC63868F5361" # TODO: Add module filename ## TODO: This hash is bad
#media_id = "4BED0DDE" http://redump.org/disc/14043

[[patch]]
    name = "60 FPS"
    desc = "Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config."
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x82BD9EB3
        value = 0x01

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 880x720."
    author = "slashiee, ICUP321, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82BAFFA4
        value = 0x38800500
    [[patch.be32]]
        address = 0x8328BB40
        value = 0x3F800000
    [[patch.be32]]
        address = 0x8328BB44
        value = 0x3F800000
    [[patch.be32]]
        address = 0x8328BB48
        value = 0x3F800000

[[patch]]
    name = "Disable Shadow Maps"
    desc = "Disables all dynamic shadows cast. Strongly improves performance at the expense of visual fidelity."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82BAD958
        value = 0x39600000

[[patch]]
    name = "Disable Depth of Field"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82BB21A4
        value = 0x60000000
    [[patch.be32]]
        address = 0x82BB20F8
        value = 0x39600000

[[patch]]
    name = "Disable Radial Blur"
    desc = "Does not disable gaussian blur, certain camera-based and per-object blur will still be rendered."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82FC1F28
        value = 0x60000000

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in README."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x820290E8
        value = 0x4018E388
