title_name = "SONIC UNLEASHED"
title_id = "53450812" # SE-2066
#hash = "" # default.xex
#media_id = ""

[[patch]]
    name = "60 FPS"
    desc = "Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config."
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x82BD24A3
        value = 0x01

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 880x720."
    author = "slashiee, ICUP321"
    is_enabled = false

    [[patch.be32]]
        address = 0x82BA9028
        value = 0x38800500
    [[patch.be32]]
        address = 0x8327B450
        value = 0x3F800000
    [[patch.be32]]
        address = 0x8327B454
        value = 0x3F800000
    [[patch.be32]]
        address = 0x8327B458
        value = 0x3F800000

[[patch]]
    name = "Disable Shadow Maps"
    desc = "Disables all dynamic shadows cast. Strongly improves performance at the expense of visual fidelity."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82BA6810
        value = 0x39600000

[[patch]]
    name = "Disable Depth of Field"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82BAB224
        value = 0x60000000
    [[patch.be32]]
        address = 0x82BAB178
        value = 0x39600000

[[patch]]
    name = "Disable Radial Blur"
    desc = "Does not disable gaussian blur, certain camera-based and per-object blur will still be rendered."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82FB9BE0
        value = 0x60000000

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in README."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x820285B8
        value = 0x4018E38E
