title_name = "Dreamcast Collection"
title_id = "5345085A" # SE-2138
hash = "19A6F930648A11C6" # default.xex
#media_id = "6876EE29" http://redump.org/disc/65367

[[patch]]
    name = "1040x720 Resolution"
    desc = "Only applies to the menu. Original resolution is 640x480."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x820887D6
        value = 0x02D0
    [[patch.be16]]
        address = 0x820887DA
        value = 0x0410
