title_name = "Tomb Raider" # TU3
title_id = "53510802" # SQ-2050
hash = "EEBBD0E3F7DDEB72" # default.xex
#media_id = [
#    "6A6BC1B7", # Disc (Russia):      http://redump.org/disc/109505
#    "03B32B71"  # Disc (USA, Europe): http://redump.org/disc/38453
#]

[[patch]]
    name = "Disable Motion Blur"
    author = "Sowa_95"
    is_enabled = false

    [[patch.be32]]
        address = 0x82000c78
        value = 0x00000000
