title_name = "Deus Ex: Human Revolution"
title_id = "535107FA"
#hash = "B9A1646F4B3D560E" # Disc 1
#hash = "82757F1D49E5724E" # Disc 2
#media_id = ""

[[patch]]
    name = "Disable Looping Audio Code"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x822B14BC
        value = 0x3B800000
