title_name = "Final Fantasy 13" # XIII
title_id = "535107E4"
#hash = "A5D9F59CD318B594" # Disc 1
#hash = "2B1B2B51196532D3" # Disc 2
#hash = "67AE4C02CC7E8FD4" # Disc 3

[[patch]]
    name = "60 FPS"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x827B6B48
        value = 0x39600001
    [[patch.be32]]
        address = 0x827B6B7C
        value = 0x39400001
