title_name = "NIER"
title_id = "535107E8"
hash = "B98F120F0DAAF44C"
#media_id = "507D2720"

[[patch]]
    name = "60 FPS"
    desc = "Readback resolve may lock the game to 30 FPS."
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x8256BB90
        value = 0x60000000
