title_name = "Ninja Gaiden II" # 2
title_id = "544307D5" # TC-2005
hash = "4CC4201C0C4ED58B" # default.xex, Japan, TU3
#media_id = "0E6FB1CE", # Disc (Japan): http://redump.org/disc/93943

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1120x584."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x83648a76
        value = 0x02d0
    [[patch.be16]]
        address = 0x83648a7a
        value = 0x0500
    [[patch.be16]]
        address = 0x837eb9f2
        value = 0x0500
    [[patch.be16]]
        address = 0x837eb9f6
        value = 0x02d0

[[patch]]
    name = "Chapter 12 Crash Workaround"
    desc = "Causes issues outside of Ch12. Use it only to skip the crash in Ch12."
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x8285a2e4
        value = 0x3bc00000
    [[patch.be32]]
        address = 0x8285a24c
        value = 0x3bc00000
