title_name = "NINJA GAIDEN 2" # TU3
title_id = "544307D5" # TC-2005
hash = "63149B7ACB1CB470" # default.xex
#media_id = ""

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1120x584."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x83648AEE
        value = 0x02D0
    [[patch.be16]]
        address = 0x837EBA46
        value = 0x02D0
    [[patch.be16]]
        address = 0x83648AF2
        value = 0x0500
    [[patch.be16]]
        address = 0x837EBA42
        value = 0x0500
