title_name = "DEAD OR ALIVE 4"
title_id = "544307D1" # TC-2001
hash = [
    "ED5C2458F214AB36", # default.xex
    "26928621530F792D"  # unlocked_default.xex
]
#media_id = "00000000"

[[patch]]
    name = "Unlock All Menus"
    author = "ryu_highabusa"
    is_enabled = false

    [[patch.be8]]
        address = 0x82414ff7
        value = 0x03

[[patch]]
    name = "Display All Character Select Icons"
    desc = "Visually reveals the full prototype roster on the character select screen. The hidden characters are shown as greyed-out icons and are not selectable."
    author = "ryu_highabusa"
    is_enabled = false

    [[patch.be32]] #show Helena
        address = 0x82aaf920
        value = 0x07010001
    [[patch.be32]] #show Ein
        address = 0x82aaf948
        value = 0x03010001
    [[patch.be32]] #show Genfu
        address = 0x82aaf970
        value = 0x06010001
    [[patch.be32]] #show Leon
        address = 0x82aaf998
        value = 0x08010001
    [[patch.be32]] #show Alpha152
        address = 0x82aaf9c0
        value = 0x10010001
    [[patch.be32]] #show Tengu
        address = 0x82aaf9e8
        value = 0x11010001
    [[patch.be32]] #show Spartan-458
        address = 0x82aafa10
        value = 0x12010001

[[patch]]
    name = "Unlock 'Jurassic Jamboree' Stage"
    author = "ryu_highabusa"
    is_enabled = false

    [[patch.be8]]
        address = 0x82417c07
        value = 0x03
