title_name = "Saints Row" # TU1
title_id = "545107D1" # TQ-2001
hash = "877C7A32ED459835" # default.xex
#media_id = "24367742"

[[patch]]
    name = "Enable Debug Console"
    desc = "Requires keyboard_passthru to be changed from false to true in the Xenia config."
    author = "emoose"
    is_enabled = false

    [[patch.be32]]
        address = 0x8265F694
        value = 0x48000AA4
    [[patch.be32]]
        address = 0x82660134
        value = 0x480B8EF9
    [[patch.be32]]
        address = 0x82660268
        value = 0x480B8E14
    [[patch.be8]]
        address = 0x835F4C3E
        value = 0x01
