title_name = "WWE All Stars"
title_id = "54510866" # TQ-2150
hash = "E4550414FD6B4F94" # Default.xex
#media_id = "60CEF505" http://redump.org/disc/60662

[[patch]]
    name = "Skip Audio Loop Stuck Code"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x833A6C98
        value = 0x38600001
