title_name = "SpongeBob: Truth or Square" # Truth-Sq.
title_id = "54510850"
hash = "D818B3AD0B84D271"
#media_id = ""

[[patch]]
    name = "Fix hang on BINK videos"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x8216AD94
        value = 0x419AFFEC
