title_name = "SpongeBob: Truth or Square" # Truth-Sq.
title_id = "54510850" # TQ-2128
#hash = "" # default.xex
#media_id = "675568DB" http://redump.org/disc/14706

[[patch]]
    name = "Fix hang on BINK videos"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x8216AD94
        value = 0x419AFFEC
