title_name = "Saints Row 2 (TU3)"
title_id = "545107FC" # TQ-2044
hash = "9B9E734BA6BDCCD9" # default.xex
#media_id = [
#    "43400270",
#    "4E854E4B", Disc (USA, Europe): http://redump.org/disc/14038
#]

[[patch]]
    name = "60 FPS"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x829384d0
        value = 0x48104aa0
    [[patch.be32]]
        address = 0x82a3cf70
        value = 0x3d403c88
    [[patch.be32]]
        address = 0x82a3cf74
        value = 0x614a8889
    [[patch.be32]]
        address = 0x82a3cf78
        value = 0x91580004
    [[patch.be32]]
        address = 0x82a3cf7c
        value = 0xc1b80004
    [[patch.be32]]
        address = 0x82a3cf80
        value = 0x4befb554

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in the README. FOV Multiplier required otherwise Vert- default are for 21:9/43:18"
    author = "Clippy95"
    is_enabled = false

    [[patch.be32]]
        address = 0x8290af6c
        value = 0x60000000
    [[patch.be32]]
        address = 0x837756b4 # 3D aspect ratio
        value = 0x4018e393
    [[patch.be32]]
        address = 0x820b80d0 # Shadows & decals aspect ratio
        value = 0x4018e393

[[patch]]
    name = "FOV Multiplier"
    desc = "Multiplies FOV. Default is 1.33333."
    author = "Clippy95"
    is_enabled = false

    [[patch.f32]]
        address = 0x82b68a4c
        value = 1.82
