title_name = "The Darkness"
title_id = "545407EE"
hash = "EDFC6F53793A6EBB"
#media_id = "0F213645"

[[patch]]
    name = "Bright Lighting Fix"
    desc = "Normalizes specular lighting and bloom exposure."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822745D0
        value = 0x3D608206
    [[patch.be32]]
        address = 0x822745E0
        value = 0xC00BC06C

# Credit to patcher Bader for FOV patch, taken from https://www.reddit.com/r/ps4homebrew/comments/o2xe6u/60fps_patch_for_ghost_of_tsushima_ps4_pro_only/h35tfuy
[[patch]]
    name = "Extended FOV"
    desc = "Increases 16:9 horizontal FOV from 90 degrees to 105 degress."
    author = "Bader"
    is_enabled = false

    [[patch.be32]]
        address = 0x8209DFF4
        value = 0x42B40000
