title_name = "Midnight Club: Los Angeles" # MCLA, Complete Edition
title_id = "545407F8" # TT-2040
hash = "D651A6BB8C7486C8" # default.xex
#media_id = "5940C9DB" http://redump.org/disc/64472/

[[patch]]
    name = "Enable Deltatime"
    desc = "Runs at any FPS with proper game speed. Can be used in conjunction with the 60 FPS patch."
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x821bdb08
        value = 0x4800012c # b 0x821bdc34

[[patch]]
    name = "Disable Motion Blur"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x8260d0b8
        value = 0x38600000 # li r3,0x0
    [[patch.be32]]
        address = 0x8260d0d4
        value = 0x38600000 # li r3,0x0

[[patch]]
    name = "60 FPS"
    desc = "Framerates higher than 60 FPS requires vsync to be changed from true to false in the Xenia config."
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x82419aa3
        value = 0x01

[[patch]]
    name = "Disable Imposter Shadows - Performance Mode"
    desc = "Trees and other foliage won't cast shadows, resulting in a moderate performance boost."
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x8230c87c
        value = 0x4800

[[patch]]
    name = "Disable MSAA"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822e4b80
        value = 0x39600001
