title_name = "Red Dead Redemption" # GOTY/Game Of The Year, Disc 1
title_id = "5454082B" # TT-2091
#hash = "" # default.xex
#media_id = "3EE87B76" http://redump.org/disc/58711

[[patch]]
    name = "Unlock FPS"
    desc = "Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x823C674C
        value = 0x48000048
    [[patch.be8]]
        address = 0x82C4E607
        value = 0x01

[[patch]]
    name = "Disable Depth of Field & Motion Blur"
    author = "illusion, boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x827E8DBC
        value = 0x4800

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822B5E10
        value = 0x38A00010

[[patch]]
    name = "360p Mode"
    desc = "Internally renders the game at 360p and upscales to 720p. Certain objects and terrain will exhibit irregular pop-in."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82770DBC
        value = 0x39600001

[[patch]]
    name = "480p Mode"
    desc = "Internally renders the game at 480p and upscales to 720p."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82770D08
        value = 0x39400001

[[patch]]
    name = "540p Mode, 4x MSAA"
    desc = "Internally renders the game at 540p, upscales to 720p and increases multisample anti-aliasing from 2x to 4x."
    author = "cornishlardon, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82770D40
        value = 0x38E00001

[[patch]]
    name = "No Trees - Performance Mode"
    desc = "Prevents trees and all other foliage from rendering. Provides a substantial performance boost."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8276CEC8
        value = 0x39600001

[[patch]]
    name = "Skip Grass Occlusion"
    desc = "Gets rid of grass."
    author = "illusion, boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x822EE494
        value = 0x4800

[[patch]]
    name = "Disable Shadows"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82927B40
        value = 0x60000000

[[patch]]
    name = "Higher Quality Post Processing"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x827D809C
        value = 0x39600001

[[patch]]
    name = "Disable SSAO"
    desc = "Probably won't improve overall performance but may help with graphical artifacts when upscaling."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822FCB40
        value = 0x48000114

[[patch]]
    name = "Skip Intro Rockstar Movie"
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x8278F56C
        value = 0x41

[[patch]]
    name = "Alternative Script Timing & Asset Garbage Collection"
    desc = "May provide a small performance boost for CPU-limited systems."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82300AD0
        value = 0x39600001
    [[patch.be32]]
        address = 0x8242011C
        value = 0x39600001

[[patch]]
    name = "Use Separate Audio Heap"
    desc = "Changes audio component heap memory. Will lower the quality of realtime audio post-processing but may provide a small performance boost for CPU-limited systems."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x823DF33C
        value = 0x39600001

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in README."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82000D7C
        value = 0x4018E38E

[[patch]]
    name = "Infinite Horse Stamina"
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82C77738
        value = 0x3C003F80
    [[patch.be32]]
        address = 0x82C7773C
        value = 0x9007000C

[[patch]]
    name = "Bottomless Clip / Infinite Gun Magazine Size"
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x825B8544
        value = 0x48000008 # Skip fsub
    [[patch.be32]]
        address = 0x825B503C
        value = 0x48000018 # Skip ammo manipulation check

[[patch]]
    name = "Infinite Ammo"
    desc = "100 in reserved magazine."
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x825B9DD4
        value = 0x3C0042C8 # Ammo amount in 2 bytes float. Default is 100. It will reset to 100 after some idle time.
    [[patch.be32]]
        address = 0x825B9DD8
        value = 0x900A0000

[[patch]]
    name = "Disable Sun Flare"
    desc = "Sun flare effect can clip through buildings when playing with increased resolutions, this prevents the effect from rendering"
    author = "emoose"
    is_enabled = false

    [[patch.be16]]
        address = 0x827833B4
        value = 0x4800
