title_name = "Far Cry Instincts: Predator" # FC
title_id = "555307DC" # US-2012
hash = "E37894C548DEFFD6" # default.xex
#media_id = "4971ECEF" http://redump.org/disc/16404

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8273E89F
        value = 0x01
