title_name = "Small Arms"
title_id = "584107D5" # XA-2005
hash = "90C49E2E1336127C" # default.xex
#media_id = "5C6ABFE7"

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1000x562."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x8219D61C
        value = 0x4280

[[patch]]
    name = "960x540 Resolution"
    desc = "Original resolution is 1000x562."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x8219D62A
        value = 0x03C0
    [[patch.be16]]
        address = 0x8219D62E
        value = 0x021C

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x8201FB54
        value = 0x4018E38E
