title_name = "Plants vs. Zombies"
title_id = "584109FF" # XA-2559
#hash = "" # TODO: Add module filename
#media_id = "528550BC"

[[patch]]
    name = "More Sunlight Please!"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x82137BF0
        value = 0x60000000

[[patch]]
    name = "No Wait Time"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x8218B464
        value = 0x60000000
