title_name = "Crazy Taxi"
title_id = "58410A34" # XA-2612
hash = "F1CD6279D0DD436A" # Content/0000000000000000/58410A34/000D0000/8CCAFCF0BCA37A5854932556831B08F3542CC94358/default.xex
#hash = "19A6F930648A11C6" # default.xex
#media_id = "26CE73AF" Crazy Taxi
#media_id = "6876EE29" Dreamcast Collection, http://redump.org/disc/65367

[[patch]]
    name = "1040x720 Resolution"
    desc = "Original resolution is 920x690. Game guest crashes above 1040x720."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x82208A46
        value = 0x02D0
    [[patch.be16]]
        address = 0x82208A4E
        value = 0x0410
