title_name = "DEADRISING 2 CASE WEST"
title_id = "58410B00"
hash = "AB92C9FE8959D527"
#media_id = "198BA306"

[[patch]]
    name = "God Mode"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x823D2F9C
        value = 0x60000000
