title_name = "Gel"
title_id = "58410908"
hash = "6F029CD15605318F"

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x8201ACCC
        value = 0x4018E38E
