title_name = "Doritos Dash of Destruction"
title_id = "5841090B"
hash = "F54D95A83765205C"
#media_id = ""

[[patch]]
    name = "Unlock FPS"
    desc = "Requires vsync to be changed from true to false in the Xenia config to go above 60 FPS."
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x820C483F
        value = 0x00
