title_name = "Hydro Thunder Hurricane"
title_id = "5841096A"
hash = "909F5A586DC17D55"
#media_id = ""

[[patch]]
    name = "Skip infinite loop on race end"
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x82379B3C
        value = 0x2F0B0000
