title_name = "Peggle"
title_id = "58410889"
hash = "83A690E6E0DA84F6"
#media_id = "111272B2"

[[patch]]
    name = "Unlimited Balls"
    author = "Credit to the creators of Peek Poker"
    is_enabled = false

    [[patch.be32]]
        address = 0x8227DA20
        value = 0x60000000
