title_name = "Outrunâ„¢ Online Arcade"
title_id = "58410968" # XA-2408
hash = "8C9CC78F50365E60" # default.xex
#media_id = "3CB8E563"

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x8209F18C
        value = 0x4018E388
